env:
  - CODECOV_TOKEN="a2b0ea09-1966-4427-8c82-c96662308164"
language: node_js
node_js:
  - "10"
sudo: false
script:
  - yarn test
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - "node_modules"
after_script:
  - yarn cov